name = "0x00"
main = "_worker.js"
compatibility_date = "2025-09-07"
keep_vars = true

[vars]
NAT64 = "2001:67c:2960:6464::/96"
PROXYIP = "di.nscl.ir"
UUID = "b9216be6-f735-4bdf-aedc-c62dd77803be"


[placement]
region = "gcp:us-west2"
# region = "aws:eu-west-2" #London
# region = "azure:japanwest" #japan
